pipeline {
    agent any
    parameters {
        BRANCH_PARAM (String, default main)
    }
    stages {
        stage('deploy') {
            when {
                branch: 'main'
            }
            steps {
                echo '${params.BRANCH_PARAM}'
            }
        }
        stage('quality') {
            parallel {
                stage('unit') {
                    steps {
                        echo 'unit'
                    }
                }
                stage('lint') {
                    steps {
                         echo 'lint'
                    }
                }
            }
        }
    }
    post {
        always {
            echo 'alw'
        }
        success {
            echo 'succ'
        }
        failure {
            echo 'fail'
        }
    }
}